connections:
  play.test1.com:
    commands:
      - "broadcast {player} joined from play.test1.com"
      - "broadcast test1"
  play.test2.com:
    commands:
      - "broadcast {player} joined from play.test2.com"
      - "broadcast test2"